[project]
name = "pizzapresence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "json5>=0.12.0",
    "pypresence>=4.3.0",
    "requests>=2.32.4",
]
